formatter:
  trailing_commas: preserve
linter:
  rules:
    prefer_single_quotes: true
    flutter_style_todos: true
    always_declare_return_types: true
    non_constant_identifier_names: false
    annotate_overrides: true
    constant_identifier_names: false
    prefer_interpolation_to_compose_strings: true
    require_trailing_commas: false
    curly_braces_in_flow_control_structures: false
    use_colored_box: false
    use_decorated_box: false
    slash_for_doc_comments: true
    sort_constructors_first: true
    unnecessary_lambdas: true
    unnecessary_late: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_rethrow_when_possible: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    prefer_void_to_null: true
